blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/weboccult/eatcard-companion/discussions/new?category=ideas
    about: Share ideas for new features
  - name: ğŸ™ Ask a Question
    url: https://github.com/weboccult/eatcard-companion/discussions/new?category=q-a
    about: Ask the community for help
  - name: ğŸ’– Share some love
    url: https://github.com/weboccult/eatcard-companion/discussions/new?category=show-and-tell
    about: Share gratitude with the team
  - name: ğŸš¨ Report Security Vulnerability
    url: https://github.com/weboccult/eatcard-companion/discussions/new?category=general
    about: Please report security vulnerabilities by email to freek@spatie.be
